### PR TITLE
feat(plugin-charts-ixora): custom series chart

### PR DESCRIPTION
**Pull request by melnikovmaksimv**
🏆 Enhancements
Add Custom Seriest Chart to Ixora Plugin Packages.  this plugin adds the following features: 
- chart by custom series without timeline, you can use any data type for series
image

### CODE REVIEW

**Comment by villebro** [comment]
@melnikovmaksimv thanks for the PR - can you add some context to the PR, e.g. a description, screenshots etc? Thank you!

**Comment by appland-streaming** [comment]
Any update here, relly intrested in the none timestamp based graph

**Comment by melnikovmaksimv** [comment]
@appland-streaming 
Yes, I will fix bugs if possible, but it can be used already
https://www.npmjs.com/package/@maksim_m/plugin-chart-ixora

**Comment by melnikovmaksimv** [comment]
> thanks for the PR - can you add some context to the PR, e.g. a description, screenshots etc? Thank you!

Absolutely, there is a lot of work now and there is no time to finish this module yet =(((

**Comment by rumbin** [comment]
@melnikovmaksimv, I am so eagerly awaiting this chart type. Please feel encouraged and motivated to tackle the remaining issues. 
Thank you very much for taking these efforts on!

**Comment by junlincc** [comment]
@melnikovmaksimv We would love to move this forward, can you provide details about this PR? Thank you for your contribution!


e.g. https://github.com/apache-superset/superset-ui/pull/801

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this PR on the main repo, which should be as simple as moving over any code changes as follows:
- core packages: `packages/**` (this repo) -> `superset-frontend/packages/**` (main repo)
- plugins: `plugins/**` (this repo) -> `superset-frontend/plugins/**` (main repo)

If you need help with the migration, please post a message on the SIP or reach out on the [community Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw).

**Pull request closed without merging**
