### PR TITLE
feat(plugin-chart-handlebars): initial commit

### PR DESCRIPTION
**Pull request by jdbranham**
* adds a new plugin, that renders the data payload
 by applying a customizable handlebars template

💔 Breaking Changes  - None

🏆 Enhancements - New Handlebars plugin

📜 Documentation - slim 😅 

image

### CODE REVIEW

**Comment by rusackas** [comment]
This is awesome!!! Thanks for tackling this! A few initial thoughts/questions:

1) Feel free to remove the default styling added by the plugin generator (the gray background, rounded corners, etc) - that was just to illustrate where one can stick in custom CSS, rather than a recommendation of actual design/styling.
2) Speaking of styling, it might be possible (first enhancement request!) to add in a CSS editor (like we do on Dashboards) to style this thing in myriad ways. I.e. Handlebars could add bad/good classes, and the CSS could render things as red/green.
3) Security issues - not sure if this provides any new vectors to grab data from the rest of a dashboard, or anything mischievous like that. Appears perfectly reasonable at first glance, but it's worth taking a close look at with that sort of mindset.

This is something that could prove VERY useful indeed. Love this contribution.

**Comment by michael-s-molina** [comment]
@jdbranham I just want to congratulate you on the excellent source code documentation. 👏🏼

**Comment by rusackas** [comment]
> ...it would be cool to add some sandboxing or extension points. That would need a thoughtful approach

100%. I was starting to look into a particular library that uses iframes for this sort of thing, and makes it easy to pass data (as props) through to them. There was a lot of CSS work to make it look as intended, though. I've been meaning to revisit this, and would be happy to set up a chat with you if you're interested in such things.

**Comment by jdbranham** [comment]
Cleaned up default styling and separated CSS from Markdown/up

Markup - 
image

Markdown - 
image

**Comment by rusackas** [comment]
I was just wishing I had this plugin, and realized I totally dropped the ball on this thread! Sorry for the long delay! 

These are the Vercel errors we're seeing. Looks like they might be pretty easy to resolve :)

image

**Comment by jdbranham** [comment]
@rusackas - I've resolved the `buildQuery` issue, and the merge conflict, but I didn't see where `validateNonEmpty` was being used.
I don't see any issues with prettier locally and the chart plugin seems to be working ok.  

I'm not sure why Vercel is still failing =\

**Comment by zhaoyongjie** [comment]
@ jdbranham Could you rebase master then force push to the repository? I saw there are 100 files changed.

**Comment by zhaoyongjie** [comment]
@jdbranham there is a dependency resolving issue in there. 
https://github.com/apache-superset/superset-ui/runs/4179937207?check_suite_focus=true

**Comment by jdbranham** [comment]
Thanks @zhaoyongjie ! 
I _think_ I can add `"react-dom": "^16.13.1"` to the peer dependencies to resolve it 🤔    
I'll try that.

**Comment by villebro** [comment]
It seems to be erroring out with this: 
image

Let us know if you need help resolving it!

**Comment by jdbranham** [comment]
My apologies! - I should've looked closer after the rebase.  
For transparency, pagination controls are not implemented 😅

**Comment by villebro** [comment]
@jdbranham so close now, but still some lint that _might_ go away with `npm run lint:fix`: 
image

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this PR on the main repo, which should be as simple as moving over any code changes as follows:
- core packages: `packages/**` (this repo) -> `superset-frontend/packages/**` (main repo)
- plugins: `plugins/**` (this repo) -> `superset-frontend/plugins/**` (main repo)

If you need help with the migration, please post a message on the SIP or reach out on the [community Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw).

**Comment by jdbranham** [comment]
Thanks @villebro - I'll move it over to the main repo

**Pull request closed without merging**
