### PR TITLE
fix(plugin-chart-echarts): fix Time-series line x-filtering not working when not rich tooltip

### PR DESCRIPTION
**Pull request by stephenLYZ**
🐛 Bug Fix
https://github.com/apache/superset/issues/16070

this is hack to make timeseries line chart clickable when tooltip trigger is 'item' (see https://echarts.apache.org/en/option.html#tooltip.trigger),  so that the chart can emit cross-filtering.

### after

https://user-images.githubusercontent.com/11830681/129067504-1ef36ba3-2a2e-49bf-b2a7-05e6b95ee4cd.mov

### CODE REVIEW

**Comment by junlincc** [comment]
Thanks @stephenLYZ, couple of question 

1. rich tooltip is incompatible with line/area/scatter on x-filtering, does this PR address all? please test all Time-series Echarts. 
2. may not be related, what happened to the legend? linebreak for space? 
Screen Shot 2021-08-11 at 1 17 56 PM

**Comment by stephenLYZ** [comment]
> Thanks @stephenLYZ, couple of question
> 
> 1. rich tooltip is incompatible with line/area/scatter on x-filtering, does this PR address all? please test all Time-series Echarts.
> 2. may not be related, what happened to the legend? linebreak for space?
> 
> Screen Shot 2021-08-11 at 1 17 56 PM

1.  Yes. All time-series echarts.
2. It seems that legend will retain linebreak and space. This is metric name: 
截屏2021-08-12 下午11 17 59

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by villebro — APPROVED** [review]
This is a really good interim solution until line hovers are properly implemented in ECharts.

**Pull request merged**
