### PR TITLE
chore: Update big number control options

### PR DESCRIPTION
**Pull request by pkdotson**
💔 Breaking Changes

🏆 Enhancements
update big number control options.
Screen Shot 2021-01-12 at 12 05 50 AM

📜 Documentation

🐛 Bug Fix

🏠 Internal

### CODE REVIEW

**Comment by ktmud** [comment]
Should we put the two checkboxes in separate lines as well?

**Comment by ktmud** [comment]
I'm also wondering instead of putting every control in its separate row, how many of these line break issues can be fixed by setting a smaller font-size for the control label.

cc @junlincc

**Comment by rusackas** [comment]
> I'm also wondering instead of putting every control in its separate row, how many of these line break issues can be fixed by setting a smaller font-size for the control label.
> 
> cc @junlincc

I think that would get us out of _some_ trouble, but it s a slippery slope. It won't likely solve all of them unless we get into teensy font territory, which would cause accessibility issues.

I think that putting each control on its own row is a good practice, and is _generally_ in the target direction of the new design.

If it does go down that road, and controls each get their own row, I think we should reconsider the `controlSetRows` layout array-of-arrays model, and consider heading toward a more responsive layout solution with CSS. But that's a bigger project!

**Review by rusackas — APPROVED** [review]
LGTM, fixes the acute issue, looks much better!

**Comment by rusackas** [comment]
@junlincc I think we can merge as is, but lemme know if you wanna hold off and handle those checkboxes. There are probably a LOT of these checkbox issues, if we want to make a sweep of them in another PR.

**Comment by ktmud** [comment]
@rusackas @junlincc do we want to update the FilterBox controls as well?

**Comment by ktmud** [comment]
May I also suggest changing the checkbox label text to sentence casing....  All caps long-text is very hard to read..

### Before



### After




cc @mihir174

**Pull request merged**
