### PR TITLE
chore: New feature flag

### PR DESCRIPTION
**Pull request by AAfghahi**
💔 Breaking Changes

🏆 Enhancements

📜 Documentation

🐛 Bug Fix

🏠 Internal
Changing the name to better reflect what the feature flag is doing.

### CODE REVIEW

**Comment by hughhhh** [comment]
@suddjian is this a breaking change we change the name of a feature flag?

**Comment by suddjian** [comment]
IMO this should be considered a breaking change (see [SIP 57](https://github.com/apache/superset/issues/12566)). It could be made a non-breaking change if measures are taken to make it so that the old name still works.

**Comment by AAfghahi** [comment]
@suddjian currently only one place in superset is using this featureFlag, and it is the database connection ui.

**Comment by eschutho** [comment]
@AAfghahi I would recommend adding the new flag instead of changing the name. You can remove the old flag later- mark that it is deprecated.

**Review by hughhhh — APPROVED** [review]

**Review by villebro — APPROVED** [review]

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this PR on the main repo, which should be as simple as moving over any code changes as follows:
- core packages: `packages/**` (this repo) -> `superset-frontend/packages/**` (main repo)
- plugins: `plugins/**` (this repo) -> `superset-frontend/plugins/**` (main repo)

If you need help with the migration, please post a message on the SIP or reach out on the [community Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw).

**Pull request closed without merging**
