### PR TITLE
feat(plugin-chart-table): add translate to chart elements

### PR DESCRIPTION
**Pull request by stuarthu**
Enable translate for some elements on table chart.
Will also update superset translate package.

🏆 Enhancements

# BEFORE
截屏2020-07-30 17 28 18

# AFTER
截屏2020-07-30 17 28 08

### CODE REVIEW

**Comment by stuarthu** [comment]
@ktmud @mistercrunch

**Comment by stuarthu** [comment]
@villebro

**Comment by ktmud** [comment]
This is does not work when 'Show' or 'entries' are used in other context when they may have different meanings. You also shouldn't import `superset-ui` in `DataTable` as there are plans to make it an independent package.

I'll make another PR to address this.

**Comment by stuarthu** [comment]
> This is does not work when 'Show' or 'entries' are used in other context when they may have different meanings. You also shouldn't import `superset-ui` in `DataTable` as there are plans to make it an independent package.
> 
> I'll make another PR to address this.

Hi @ktmud , if it needs more than 1 week to address this, can we submit this PR first to solve the translation issue and refactor later?

**Pull request closed without merging**
