### PR TITLE
feat: adding requiresTime type

### PR DESCRIPTION
**Pull request by rusackas**
💔 Breaking Changes

🏆 Enhancements

Adds typing for the requiresType property, on ControlPanelConfig, in the chart-controls pkg.

📜 Documentation

🐛 Bug Fix

🏠 Internal

### CODE REVIEW

**Comment by ktmud** [comment]
I see this property defined for a lot of charts, but couldn't find it in the actual code---bother frontend or backend. Could you point me to the code piece where it was used if there's any? (Otherwise maybe cleanup?)

**Comment by rusackas** [comment]
You're right, I'm not seeing its purpose either. Maybe @villebro has some insight here.

**Comment by rusackas** [comment]
I think you may be right... it _seems_ like the plugin works just fine without the `requireTime` param. I'll just leave this PR hanging out here for a little while, press on with the generator PR, and maybe we can go through and I'll open a PR deleting `requireTime` everywhere, to see how that goes.

**Comment by villebro** [comment]
I've never seen it being used anywhere, so AFAIK it's probably ok to remove it.

**Comment by ktmud** [comment]
Per discussion, removed it instead

**Pull request closed without merging**
