### PR TITLE
refactor: replace yarn with npm

### PR DESCRIPTION
**Pull request by zhaoyongjie**
💔 Breaking Changes
- replace `yarn` with `npm` and remove dependency on `yarn`
- bump `eslint` from 7.17.0 to 7.32.0
- bump `prettier` from 2.2.1 to 2.4.1
- remove `@storybook/addon-info` in superset-ui-demo as it isn't available on Storybook 6 and wasn't being used
- remove dependency on `@superset-ui/legacy-plugin-chart-word-cloud` in superset-ui-demo (has been superseded by `@superset-ui/plugin-chart-word-cloud`)
- freeze@encodable/color to 1.1.1 in superset-ui-demo

If you want to test this PR in local, please run commands in terminal
```
rm -rf ./{packages,plugins}/*/node_modules ./node_modules
rm -rf ./{packages,plugins}/*/yarn.lock ./yarn.lock
rm -rf ./{packages,plugins}/*/esm ./{packages,plugins}/*/lib
rm -rf ./{packages,plugins}/*/yarn-error.log ./yarn.lock
rm -rf ./{packages,plugins}/*/tsconfig.tsbuildinfo ./tsconfig.tsbuildinfo
```

refer to: [[SIP-14] remove dependency on "Yarn" package in favor of npm](https://github.com/apache/superset/issues/6217)

### CODE REVIEW

**Comment by zhaoyongjie** [comment]
> @zhaoyongjie Can you add a reference to [SIP-14](https://github.com/apache/superset/issues/6217) in the PR's description?

Sure. Thanks.

**Comment by villebro** [comment]
> Why are we replacing? How is it align with monorepo project?

@amitmiran137 We're using `npm` on the main repo (see SIP-14: https://github.com/apache/superset/issues/6217), and to simplify the toolchain, it makes sense to fully migrate to `npm` now. Yarn has also proven to be very bad at handling dependency resolution, due to which we're, among others, on incompatible versions of React for the current version of AntD (4.9.4 requires 17.x, we're on >=16.13).

**Comment by zhaoyongjie** [comment]
> FYI the vercel storybook preview shows a broken chart for the legacy calendar. Not sure if it's related. Legacy_Chart_Plugins___legacy-plugin-chart-calendar_-_Basic_⋅_Storybook

The issues of Storybook will open separated PR to fix.

**Comment by zhaoyongjie** [comment]
> I left a few comments where npm ci would be better than npm install (mostly suggestions). But the release workflow is prob the most important one as npm doesn't have a --frozen-lockfile flag on `install`, it's essentially `npm ci`.

Nice catch. I am going to update this PR.

**Comment by villebro** [comment]
🎉 !

**Pull request merged**
