### PR TITLE
feat(plugin-chart-echarts): add x-filtering to treemap

### PR DESCRIPTION
**Pull request by stephenLYZ**
🏆 Enhancements

This PR adds x-filtering to the treemap. 

Case 1: when a rectangular area is clicked, the transparency of other areas will decrease to highlight the clicked area.
Case 2: canceling all the highlighted areas will be restored to their original state.

link to [project card](https://github.com/apache/superset/projects/13#card-59950549)

### Screenshot

https://user-images.githubusercontent.com/11830681/118941999-e55f9400-b984-11eb-9e12-11c357e33263.mov

### CODE REVIEW

**Comment by stephenLYZ** [comment]
cc @zhaoyongjie @villebro @junlincc @xiezhongfu

**Comment by junlincc** [comment]
@stephenLYZ thanks for the PR!

- I am not seeing receiving filtering indicator(blue) on charts 
- the expected behavior is emitting filtering event one series at a time. 

@villebro please chime in/~

**Comment by stephenLYZ** [comment]
> @stephenLYZ thanks for the PR!
> 
> * I am not seeing receiving filtering indicator(blue) on charts
> * the expected behavior is emitting filtering event one series at a time.
> 
> @villebro please chime in/~

The first problem has been solved. Regarding the second question, is this the expected behavior?

https://user-images.githubusercontent.com/11830681/118941999-e55f9400-b984-11eb-9e12-11c357e33263.mov

**Review by junlincc — APPROVED** [review]
Product signed off

**Review by zhaoyongjie — APPROVED** [review]
Looks nice! leaves some follow-up.

**Pull request merged**
