### PR TITLE
feat(legacy-plugin-chart-country-map): added finland map

### PR DESCRIPTION
**Pull request by Anushka-Hapukotuwa**
🏆 Enhancements - added finland map (partial)

### CODE REVIEW

**Comment by villebro** [comment]
Thanks @Anushka-Hapukotuwa for this PR 🇫🇮! Would you be open to adding the rest of the missing regions? https://en.wikipedia.org/wiki/ISO_3166-2:FI

**Comment by Anushka-Hapukotuwa** [comment]
@villebro This pull request was created for a testing purpose. If this is successful, can add the complete geojson file with all the regions.

**Comment by Anushka-Hapukotuwa** [comment]
Complete finland geojson with ISO codes added

**Review by villebro — APPROVED** [review]
LGTM, kiitos paljon! 🇫🇮

**Pull request merged**
