### PR TITLE
feat(plugin-chart-echarts): add only_total control to ts chart

### PR DESCRIPTION
**Pull request by stephenLYZ**
🏆 Enhancements
releated to https://github.com/apache-superset/superset-ui/pull/1279
closes https://github.com/apache/superset/issues/16063

#### individual values
image

#### total values
image

### CODE REVIEW

**Comment by villebro** [comment]
@stephenLYZ I'm unable to disable "Only total" on bar chart: 
image
Also, for non-stacked it's showing the total on all labels:
image

**Comment by stephenLYZ** [comment]
> @stephenLYZ I'm unable to disable "Only total" on bar chart:
> image
> Also, for non-stacked it's showing the total on all labels:
> image

**Comment by stephenLYZ** [comment]
@villebro  Oh sorry! I think I misunderstood this feature. The total value is only for stacked bars, right? Like this: 

image

image

**Comment by villebro** [comment]
> @villebro Oh sorry! I think I misunderstood this feature. The total value is only for stacked chart, right? Like this:

@stephenLYZ yes, precisely 👍  So when stacking is disabled, the "Only total" control will be invisible. And when stacking, it will be available, and only show the total on the top if selected - otherwise it will show the series values (not summed). I think your screenshots look correct!

**Review by villebro — APPROVED** [review]
@stephenLYZ this works perfectly! However, CI appears to be failing. LGTM once CI passes

**Comment by junlincc** [comment]
great work! @stephenLYZ

**Pull request merged**
