### PR TITLE
fix(plugin-chart-echarts): include label length in distance calculation

### PR DESCRIPTION
**Pull request by krsnik93**
🐛 Bug Fix
Fixes labels overlapping axis as reported here: https://github.com/apache/superset/pull/14072#issuecomment-818920134

Label length (in chars) is now taken into account when calculating distance from axis.

Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by villebro** [comment]
@krsnik93 this needs a rebase

**Comment by krsnik93** [comment]
@villebro thanks, done

**Comment by krsnik93** [comment]
@villebro hello, would you have some time to take a look at this?

**Review by villebro — APPROVED** [review]
LGTM - when there is some spare time let's try to add native support for improved text alignment to the gauge series type in ECharts.

**Pull request merged**
