### PR TITLE
feat(plugin-chart-echarts): Treemap improvements

### PR DESCRIPTION
**Pull request by stephenLYZ**
🏆 Enhancements
- contribution mode show % of parent in the tooltip
- change upper label color to white
- remove label position control
- support only one metric

image

### CODE REVIEW

**Comment by junlincc** [comment]
@stephenLYZ this is great!! 
please provide screenshot for each new feature. i think showing % in tooltip is sufficient without adding contribution mode

**Comment by zhaoyongjie** [comment]
What does the largest color block represent? How are multiple metrics represented on the treemap?

image

**Comment by zhaoyongjie** [comment]
not using order by correctly

image

**Comment by stephenLYZ** [comment]
> What does the largest color block represent? How are multiple metrics represented on the treemap?
> 
> image

I think we can only use one metric(first one) for the treemap viz cause this defines the size (% of total) of each rectangle in one dimension. Maybe we can place the other metrics in the label or tooltip. @junlincc What do u think about it?

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Pull request merged**
