### PR TITLE
chore: bump mathjs to latest version on all plugins

### PR DESCRIPTION
**Pull request by villebro**
Bump `mathjs` to the latest version (`8.0.1`) and make required code changes. Verified to work locally.

### CODE REVIEW

**Review by rusackas — APPROVED** [review]

**Comment by ktmud** [comment]
do we know if the new version breaks any of the existing formulas? (Happy to pull some sample data from Airbnb users if needed)

**Comment by villebro** [comment]
@ktmud I don't believe the evaluation logic itself has changed, only the function name. I tested with some simple ones `sin(x)`, constant values etc, all worked fine.

**Comment by villebro** [comment]
..having said that, I'd be thankful for some real test cases so I can add them to the test suite. Btw, I'll be moving all annotation logic to `superset-ui-core` from the ECharts plugin once this development stabilizes.

**Comment by ktmud** [comment]
Just pulled example formulas from our production data and didn't see any complex formulas we should be worry about:

```
SELECT
  id,
  slice_name,
  viz_type,
  json_extract_scalar(params, '$.annotation_layers[0].value'),
  params 
FROM "db_exports"."superset_production_slices_v01"
WHERE "ds" = '2020-11-11'
  AND params like '%FORMULA%'
  AND not regexp_like(json_extract_scalar(params, '$.annotation_layers[0].value'), '^[\d\.]*$')
LIMIT 1000
```

Of tens of thousands of slices, there are only ~100 charts used real computational formulas (that is not a static number) in a FORMULA annotation layer.

**Pull request merged**
