### PR TITLE
feat:  remove the default Y-axis truncate in bar chart

### PR DESCRIPTION
**Pull request by stephenLYZ**
remove the default Y-axis truncate check box to “unchecked” and add a tooltip next to the checkbox saying “It’s not recommended to truncate y-axis in Bar chart”

image

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
@junlin code LGTM. one nite: should we keep all echart timeseries viz consistent for this control?

**Comment by villebro** [comment]
For context, y-axis truncation was enabled by default only because it was default behavior in the NVD3 charts. I'm personally against truncation of y-axes by default (I think it's ok in certain cases, but should be a conscious decision), so I'd be happy to see truncation being disabled by default in all charts. But I assume there may be community resistance to this, as changing these types of things have historically proven to be a fairly sensitive topic.

**Review by villebro — COMMENTED** [review]
Code changes LGTM, but let's think this through once more before merging to make sure we have broad alignment for changing the default behavior.

**Comment by junlincc** [comment]
Is the tooltip only showing in bar chart? if both behaviors 1)not set by default 2) showing tooltip are only showing in Bar chart, i think we are good.

**Comment by zhaoyongjie** [comment]
> Is the tooltip only showing in bar chart? if both behaviors 1)not set by default 2) showing tooltip are only showing in Bar chart, i think we are good.

So, Do we change the `truncate y-axis` control to uncheck in all echart viz?

**Pull request merged**
