### PR TITLE
feat(chart-controls): d3 formatting with .2% #1274

### PR DESCRIPTION
**Pull request by jayakrishnankk**
💔 Breaking Changes: No

🏆 Enhancements: add .2% D3 formatting

📜 Documentation: NA

🐛 Bug Fix: NA

🏠 Internal: NA

### CODE REVIEW

**Comment by jayakrishnankk** [comment]
`codecov/project/core-packages-ts` workflow did not report the status. Can someone with privileges be able to run it again ?

**Review by villebro — APPROVED** [review]
LGTM

**Comment by jayakrishnankk** [comment]
@villebro - a process question, since this is my first pull request.

I hope this will get merged at some point to the master. Is there any additional step that I need to do ?

Thanks in advance.

**Comment by villebro** [comment]
This slipped between the cracks - thanks for your patience!

**Pull request merged**
