### PR TITLE
feat: add syria to Country Maps

### PR DESCRIPTION
**Pull request by Reslan-Tinawi**
🏆 Enhancements

Add `Syria` map, to be used in the `CountrMap` visualization.

The map is downloaded from [DIVA-GIS](https://www.diva-gis.org/gdata) and converted to `geojson` using this [tool](https://ogre.adc4gis.com/).

### CODE REVIEW

**Comment by Reslan-Tinawi** [comment]
@ktmud / @rusackas 
This is my first contribution to open source, would you please take a look at the PR, and give me some guidelines.
Thanks :grinning:

**Review by ktmud — COMMENTED** [review]
Thanks for the contribution, @Reslan-Tinawi , and congrats on PR #1000! Always nice to see a new contributor from around the world.

Not sure why, but it seems the geo boundary does not align well with OSM data:



Could you add note about your datasource in PR description just for reference?

**Comment by kristw** [comment]
image

The preview shows that the map file does not work.

**Comment by Reslan-Tinawi** [comment]
@ktmud I've updated the PR description, also, I updated the map.

@kristw Thanks for your note, I wasn't aware it wasn't working. I updated the map now and tested on storybook, and it's working now :)

**Comment by Reslan-Tinawi** [comment]
@villebro could you please take a look at this PR :grinning: 
Thanks :pray:

**Review by ktmud — APPROVED** [review]

**Pull request merged**
