### PR TITLE
feat(core): boring smart date formatting

### PR DESCRIPTION
**Pull request by ktmud**
💔 Breaking Changes

🏆 Enhancements

Make the smart date formatter "boring"---return a more complete (and accurate) but less adaptive (and sometimes longer) representation of the timestamp.

The reason for this change is that time marks like `".111ms"` or `".13s"` are of little use in most business context.

Sometimes the format also doesn't make sense when it is applied to x-axis bounds:

(It's impossible to tell which month `Mon 06` is referring to).

### Before

before-adaptive

### After

adaptive-formatting

### CODE REVIEW

**Comment by ktmud** [comment]
This is breaking change. I'll update the test cases if folks think this is the right way to go.

**Review by junlincc — APPROVED** [review]
make sense from the product standpoint, also checked with end-users to confirm this is direction we wanna go. thanks for the improvement! @ktmud 🙏

**Comment by ktmud** [comment]
One concern with this may introduce very long x-axis ticks for xy charts (line, bar, area, etc.).

After discussing this with @kristw ,  I'm inclined to limit this to table charts only and leave the work for smarter axis labels to later.

**Comment by villebro** [comment]
I think the old behavior is better for the x-axis on D3 charts, as it adapts the ticks to fit well with the truncated format. Not sure how we'd do this more elegantly, but it seems like "smart" should apply the one proposed here whenever it's used as pure text (tooltips, tables) but the old one when used on chart axes.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this PR on the main repo, which should be as simple as moving over any code changes as follows:
- core packages: `packages/**` (this repo) -> `superset-frontend/packages/**` (main repo)
- plugins: `plugins/**` (this repo) -> `superset-frontend/plugins/**` (main repo)

If you need help with the migration, please post a message on the SIP or reach out on the [community Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw).

**Pull request closed without merging**
